site_name: Apache Spark Connector for Lance
site_description: The Apache Spark Connector for Lance allows Apache Spark to efficiently read datasets stored in Lance format.
site_url: https://lancedb.github.io/lance-spark/
docs_dir: src

repo_name: lancedb/lance-spark
repo_url: https://github.com/lancedb/lance-spark

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lancedb/lance-spark
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zMM32dvNtd
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lancedb

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Requirements: getting-started/requirements.md
  - User Guide:
    - Reading Lance Datasets: user-guide/reading-datasets.md
    - Writing Lance Datasets: user-guide/writing-datasets.md
    - Configuration: user-guide/configuration.md
    - Performance Tuning: user-guide/performance.md
    - Examples: user-guide/examples.md
  - Development:
    - Building from Source: development/building.md
    - Multi-Version Support: development/multi-version.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - Reference:
    - API Reference: reference/api.md
    - Supported Features: reference/features.md
    - Troubleshooting: reference/troubleshooting.md