name: Spark Unit Tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  # This env var is used by Swatinem/rust-cache@v2 for the cache
  # key, so we set it to make sure it is always consistent.
  CARGO_TERM_COLOR: always
  # Disable full debug symbol generation to speed up CI build and keep memory down
  # "1" means line tables only, which is useful for panic tracebacks.
  RUSTFLAGS: "-C debuginfo=1"
  RUST_BACKTRACE: "1"
  # according to: https://matklad.github.io/2021/09/04/fast-rust-builds.html
  # CI builds are faster with incremental disabled.
  CARGO_INCREMENTAL: "0"
  CARGO_BUILD_JOBS: "1"

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]
        scala-version: [ 2.12 ]
        spark-version: [ 3.4, 3.5 ]
    steps:
      - name: Install Sudo if using act for local testing
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libssl-dev
      - name: Install NodeJS if using act for local testing
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install nodejs
      - name: Checkout lance repository
        uses: actions/checkout@v4
        with:
          repository: lancedb/lance
          path: lance
      - name: Checkout lance-spark repo
        uses: actions/checkout@v4
        with:
          path: lance-spark
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: "maven"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: lance/java/core/lance-jni
      - name: Setup Java tool options for higher Java versions
        working-directory: lance/java
        run: |
          if [ "${{ matrix.java-version }}" == "17" ]; then
            export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS \
            -XX:+IgnoreUnrecognizedVMOptions \
            --add-opens=java.base/java.lang=ALL-UNNAMED \
            --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
            --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
            --add-opens=java.base/java.io=ALL-UNNAMED \
            --add-opens=java.base/java.net=ALL-UNNAMED \
            --add-opens=java.base/java.nio=ALL-UNNAMED \
            --add-opens=java.base/java.util=ALL-UNNAMED \
            --add-opens=java.base/java.util.concurrent=ALL-UNNAMED \
            --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
            --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED \
            --add-opens=java.base/sun.nio.ch=ALL-UNNAMED \
            --add-opens=java.base/sun.nio.cs=ALL-UNNAMED \
            --add-opens=java.base/sun.security.action=ALL-UNNAMED \
            --add-opens=java.base/sun.util.calendar=ALL-UNNAMED \
            --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED \
            -Djdk.reflect.useDirectMethodHandle=false \
            -Dio.netty.tryReflectionSetAccessible=true"
          fi
      - name: Install Lance Java SDK
        working-directory: lance/java
        run: mvn clean install -pl :lance-core -DskipTests -am
      - name: Running tests with Java ${{ matrix.java-version }} Scala ${{matrix.scala_version }} for Spark ${{ matrix.spark_version }}
        working-directory: lance-spark
        run: ./mvnw clean install -Pspark-${{ matrix.spark_version }} -Pscala-${{ matrix.scala_version }} -pl lance-spark-${{ matrix.spark_version }} -am
